version: '3'
services:
  front-end:
    image: node:16-alpine
    container_name: login_front_end
    working_dir: /app
    volumes: 
    - ./front-end:/app
# o stdin_open e tty serve para espelhar informacoes do container para maquina 
    stdin_open: true
    tty: true
    command: sh
    ports:
    - 3000:3000
    restart: on-failure