version: '3'
services:
  front-end:
#para rodar o que esta no Dockerfile usamos build
    build: front-end/
    container_name: front_end_login
    working_dir: /app
    volumes:
      - ./front-end:/app
    stdin_open: true
    tty: true
    command: sh
    ports:
      - 3000:3000
    restart: on-failure